connections:
  delta_dte10t:
    params:
      baudrate: 115200
      bytesize: 8
      parity: E
      port: COM8
      slave_id: 1
      stopbits: 1
    type: modbus_rtu
  delta_tc_rtu:
    params:
      baudrate: 38400
      bytesize: 7
      parity: E
      port: COM23
      slave_id: 1
      stopbits: 1
      timeout: 1.0
    type: modbus_ascii
  keyence_plc1:
    params:
      host: 192.168.2.40
      port: 8501
      unit: 0
    type: keyence
poll_interval: 1.0
tasks:
- byte_order: abcd
  channel_name: DTE_CH5当前温度
  channel_prefix: pv_ch5
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4100
  task_id: task_dte_pv_ch5
  unit: °C
- byte_order: abcd
  channel_name: DTE_CH6当前温度
  channel_prefix: pv_ch6
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4101
  task_id: task_dte_pv_ch6
  unit: °C
- byte_order: abcd
  channel_name: DTE_CH7当前温度
  channel_prefix: pv_ch7
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4102
  task_id: task_dte_pv_ch7
  unit: °C
- byte_order: abcd
  channel_name: DTE_CH8当前温度
  channel_prefix: pv_ch8
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4103
  task_id: task_dte_pv_ch8
  unit: °C
- byte_order: abcd
  channel_name: DTE_CH5当前温度
  channel_prefix: pv_ch5
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4100
  task_id: task_dte_pv_ch5
  unit: °C
- byte_order: abcd
  channel_name: DTE_CH6当前温度
  channel_prefix: pv_ch6
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4101
  task_id: task_dte_pv_ch6
  unit: °C
- byte_order: abcd
  channel_name: DTE_CH7当前温度
  channel_prefix: pv_ch7
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4102
  task_id: task_dte_pv_ch7
  unit: °C
- byte_order: abcd
  channel_name: DTE_CH8当前温度
  channel_prefix: pv_ch8
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4103
  task_id: task_dte_pv_ch8
  unit: °C
- byte_order: abcd
  channel_name: DTE_CH5设定温度
  channel_prefix: sv_ch5
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4108
  task_id: task_dte_sv_ch5
  unit: °C
- byte_order: abcd
  channel_name: DTE_CH6设定温度
  channel_prefix: sv_ch6
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4109
  task_id: task_dte_sv_ch6
  unit: °C
- byte_order: abcd
  channel_name: DTE_CH7设定温度
  channel_prefix: sv_ch7
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4110
  task_id: task_dte_sv_ch7
  unit: °C
- byte_order: abcd
  channel_name: DTE_CH8设定温度
  channel_prefix: sv_ch8
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4111
  task_id: task_dte_sv_ch8
  unit: °C
- byte_order: abcd
  channel_name: DTE_CH5输出功率1
  channel_prefix: out1_ch5
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4212
  task_id: task_dte_out1_ch5
  unit: '%'
- byte_order: abcd
  channel_name: DTE_CH6输出功率1
  channel_prefix: out1_ch6
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4213
  task_id: task_dte_out1_ch6
  unit: '%'
- byte_order: abcd
  channel_name: DTE_CH7输出功率1
  channel_prefix: out1_ch7
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4214
  task_id: task_dte_out1_ch7
  unit: '%'
- byte_order: abcd
  channel_name: DTE_CH8输出功率1
  channel_prefix: out1_ch8
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4215
  task_id: task_dte_out1_ch8
  unit: ''
- byte_order: abcd
  channel_name: DTE_CH5输出功率2
  channel_prefix: out2_ch5
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4220
  task_id: task_dte_out2_ch5
  unit: '%'
- byte_order: abcd
  channel_name: DTE_CH6输出功率2
  channel_prefix: out2_ch6
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4221
  task_id: task_dte_out2_ch6
  unit: '%'
- byte_order: abcd
  channel_name: DTE_CH7输出功率2
  channel_prefix: out2_ch7
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4222
  task_id: task_dte_out2_ch7
  unit: '%'
- byte_order: abcd
  channel_name: DTE_CH8输出功率2
  channel_prefix: out2_ch8
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4223
  task_id: task_dte_out2_ch8
  unit: '%'
- byte_order: abcd
  channel_name: DTM_通道5 PV值
  channel_prefix: ch5
  connection_id: delta_tc_rtu
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 620
  task_id: task_dtm_ch5_pv
  unit: °C
- byte_order: abcd
  channel_name: DTM_通道5 SV值
  channel_prefix: ch5
  connection_id: delta_tc_rtu
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4
  task_id: task_dtm_ch5_sv
  unit: °C
- byte_order: abcd
  channel_name: DTM_通道5 输出1
  channel_prefix: ch5
  connection_id: delta_tc_rtu
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 636
  task_id: task_dtm_ch5_out1
  unit: '%'
- byte_order: abcd
  channel_name: DTM_通道5 输出2
  channel_prefix: ch5
  connection_id: delta_tc_rtu
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 644
  task_id: task_dtm_ch5_out2
  unit: '%'
- byte_order: abcd
  channel_name: DTM_通道6 PV值
  channel_prefix: ch6
  connection_id: delta_tc_rtu
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 621
  task_id: task_dtm_ch6_pv
  unit: °C
- byte_order: abcd
  channel_name: DTM_通道6 SV值
  channel_prefix: ch6
  connection_id: delta_tc_rtu
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 5
  task_id: task_dtm_ch6_sv
  unit: °C
- byte_order: abcd
  channel_name: DTM_通道6 输出1
  channel_prefix: ch6
  connection_id: delta_tc_rtu
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 637
  task_id: task_dtm_ch6_out1
  unit: '%'
- byte_order: abcd
  channel_name: DTM_通道6 输出2
  channel_prefix: ch6
  connection_id: delta_tc_rtu
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 645
  task_id: task_dtm_ch6_out2
  unit: '%'
- byte_order: abcd
  channel_name: DTM_通道7 PV值
  channel_prefix: ch7
  connection_id: delta_tc_rtu
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 622
  task_id: task_dtm_ch7_pv
  unit: °C
- byte_order: abcd
  channel_name: DTM_通道7 SV值
  channel_prefix: ch7
  connection_id: delta_tc_rtu
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 6
  task_id: task_dtm_ch7_sv
  unit: °C
- byte_order: abcd
  channel_name: DTM_通道7 输出1
  channel_prefix: ch7
  connection_id: delta_tc_rtu
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 638
  task_id: task_dtm_ch7_out1
  unit: '%'
- byte_order: abcd
  channel_name: DTM_通道7 输出2
  channel_prefix: ch7
  connection_id: delta_tc_rtu
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 646
  task_id: task_dtm_ch7_out2
  unit: '%'
- byte_order: abcd
  channel_name: DTM_通道8 PV值
  channel_prefix: ch8
  connection_id: delta_tc_rtu
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 623
  task_id: task_dtm_ch8_pv
  unit: °C
- byte_order: abcd
  channel_name: DTM_通道8 SV值
  channel_prefix: ch8
  connection_id: delta_tc_rtu
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 7
  task_id: task_dtm_ch8_sv
  unit: °C
- byte_order: abcd
  channel_name: DTM_通道8 输出1
  channel_prefix: ch8
  connection_id: delta_tc_rtu
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 639
  task_id: task_dtm_ch8_out1
  unit: '%'
- byte_order: abcd
  channel_name: DTM_通道8 输出2
  channel_prefix: ch8
  connection_id: delta_tc_rtu
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 647
  task_id: task_dtm_ch8_out2
  unit: '%'
write_tasks:
- byte_order: abcd
  connection_id: keyence_plc1
  connection_type: keyence
  data_type: uint16
  device_type: DM
  name: 写值任务
  start_addr: 0
  task_id: wtask_1785413955422
  value: 0.0
  write_interval: 1.0
- byte_order: abcd
  connection_id: delta_dte10t
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  name: 写值任务
  start_addr: 0
  task_id: wtask_1785414064205
  value: 0.0
  write_interval: 1.0
- byte_order: abcd
  connection_id: delta_tc_rtu
  connection_type: modbus_ascii
  data_type: uint16
  device_type: holding
  name: 写值任务
  start_addr: 0
  task_id: wtask_1785414074273
  value: 0.0
  write_interval: 1.0
