calc_tasks:
- channel_name: 上层实时CH3
  channel_prefix: calc_live_ch3
  formula: task_sv_ch3*10+(170-task_temp_ch4)*5
  offset: 0.0
  scale: 1.0
  task_id: calc_1785919067203
  unit: ℃
- channel_name: 下层实时CH1
  channel_prefix: calc_live_ch1
  formula: task_sv_ch1*10+(170-task_temp_ch1)*5
  offset: 0.0
  scale: 1.0
  task_id: calc_1785919067200
  unit: ℃
- channel_name: 上层实时CH4
  channel_prefix: calc_live_ch4
  formula: task_sv_ch4*10+(task_temp_ch4-task_temp_ch6)*5
  offset: 0.0
  scale: 1.0
  task_id: calc_live_ch4_1785919067204
  unit: ℃
- channel_name: 下层实时CH2
  channel_prefix: calc_live_ch2
  formula: task_sv_ch2*10+(task_temp_ch1-task_temp_ch3)*5
  offset: 0.0
  scale: 1.0
  task_id: calc_live_ch2_1785919067201
  unit: ℃
- channel_name: 上层实时CH3与设定温度差
  channel_prefix: calc_live_ch3_diff
  formula: task_sv_ch3+(-task_temp_ch3)
  offset: 0.0
  scale: 1.0
  task_id: calc_1785919067205
  unit: ℃
- channel_name: 下层实时CH1与设定温度差
  channel_prefix: calc_live_ch1_diff
  formula: task_sv_ch1+(-task_temp_ch1)
  offset: 0.0
  scale: 1.0
  task_id: calc_1785919067204
  unit: ℃
- channel_name: 上层倾斜
  channel_prefix: calc_upper_tilt
  formula: task_temp_ch4-task_temp_ch6
  offset: 0.0
  scale: 1.0
  task_id: calc_1785919067206
  unit: ℃
- channel_name: 下层倾斜
  channel_prefix: calc_lower_tilt
  formula: task_temp_ch1-task_temp_ch3
  offset: 0.0
  scale: 1.0
  task_id: calc_1785919067202
  unit: ℃
- channel_name: 上层中心差
  channel_prefix: calc_upper_center_diff
  formula: (task_temp_ch5*2-task_temp_ch4-task_temp_ch6)*0.5
  offset: 0.0
  scale: 1.0
  task_id: calc_center_1785919067207
  unit: ℃
- channel_name: 下层中心差
  channel_prefix: calc_lower_center_diff
  formula: (task_temp_ch2*2-task_temp_ch1-task_temp_ch3)*0.5
  offset: 0.0
  scale: 1.0
  task_id: calc_center_1785919067208
  unit: ℃
- channel_name: 下层PWM调节值
  channel_prefix: calc_lower_pwm
  formula: heater_duty_lower_mid-(task_temp_ch2*2-task_temp_ch1-task_temp_ch3)*0.5
  offset: 0.0
  scale: 1.0
  task_id: calc_pwm_1785919067209
  unit: '%'
- channel_name: 中层下面PWM调节值
  channel_prefix: calc_mid_lower_pwm
  formula: heater_duty_mid_lower_mid-(task_temp_ch5*2-task_temp_ch4-task_temp_ch6)*0.5  
  offset: 0.0
  scale: 1.0
  task_id: calc_pwm_1785919067210
  unit: '%'
calc_write_tasks:
- byte_order: abcd
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  name: 设置CH1设定温度SV
  source_task_id: calc_1785919067200
  start_addr: 4104
  task_id: calcwrite_1785919993452
  write_interval: 2000.0
- byte_order: abcd
  name: 下层PWM调节值
  connection_id: pwm_plc1
  connection_type: keyence
  source_task_id: calc_pwm_1785919067209
  data_type: uint16
  device_type: DM
  start_addr: 15100
  task_id: pwm_pwm
  write_interval: 500.0
- byte_order: abcd
  name: 中层下面PWM调节值
  connection_id: pwm_plc1
  connection_type: keyence
  source_task_id: calc_pwm_1785919067210
  data_type: uint16
  device_type: DM
  start_addr: 15102
  task_id: pwm_mid_lower
  write_interval: 500.0
- byte_order: abcd
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  name: 设置CH2设定温度SV
  source_task_id: calc_live_ch2_1785919067201
  start_addr: 4105
  task_id: calc_write_sv_ch2_1785919993453
  write_interval: 2000.0
- byte_order: abcd
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  name: 设置CH4设定温度SV
  source_task_id: calc_live_ch4_1785919067204
  start_addr: 4106
  task_id: calc_write_sv_ch4_1785919993455
  write_interval: 2000.0
- byte_order: abcd
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  name: 设置CH3设定温度SV
  source_task_id: calc_1785919067203
  start_addr: 4106
  task_id: calc_write_sv_ch3_1785919993454
  write_interval: 2000.0
connections:
  dte_rtu_com9:
    params:
      baudrate: 115200
      bytesize: 8
      parity: E
      port: COM9
      slave_id: 1
      stopbits: 1
      timeout: 1.0
    type: modbus_rtu
  pt100_rtu_com11:
    params:
      baudrate: 9600
      bytesize: 8
      parity: N
      port: COM11
      slave_id: 0
      stopbits: 1
      timeout: 1.0
    type: modbus_rtu
  pwm_plc1:
    params:
      host: 192.168.2.80
      port: 8501
      timeout: 3.0
      unit: 0
    type: keyence
poll_interval: 60.0
tasks:
- byte_order: abcd
  channel_name: 第1路温度
  channel_prefix: temp_ch1
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.01
  start_addr: 0
  task_id: task_temp_ch1
  unit: °C
- byte_order: abcd
  channel_name: 第2路温度
  channel_prefix: temp_ch2
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.01
  start_addr: 1
  task_id: task_temp_ch2
  unit: °C
- byte_order: abcd
  channel_name: 第3路温度
  channel_prefix: temp_ch3
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.01
  start_addr: 2
  task_id: task_temp_ch3
  unit: °C
- byte_order: abcd
  channel_name: 第4路温度
  channel_prefix: temp_ch4
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.01
  start_addr: 3
  task_id: task_temp_ch4
  unit: °C
- byte_order: abcd
  channel_name: 第5路温度
  channel_prefix: temp_ch5
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.01
  start_addr: 4
  task_id: task_temp_ch5
  unit: °C
- byte_order: abcd
  channel_name: 第6路温度
  channel_prefix: temp_ch6
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.01
  start_addr: 5
  task_id: task_temp_ch6
  unit: °C
- byte_order: abcd
  channel_name: CH1设定温度
  channel_prefix: sv_ch1
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4104
  task_id: task_sv_ch1
  unit: °C
- byte_order: abcd
  channel_name: CH2设定温度
  channel_prefix: sv_ch2
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4105
  task_id: task_sv_ch2
  unit: °C
- byte_order: abcd
  channel_name: 下层中间两个加热棒占空比DM15100
  channel_prefix: lower_mid_heater
  connection_id: pwm_plc1
  connection_type: keyence
  data_type: uint16
  device_type: DM
  offset: 0
  quantity: 1
  scale: 1.0
  start_addr: 15100
  task_id: heater_duty_lower_mid
  unit: '%'
- byte_order: abcd
  channel_name: 中层下面中间两个加热棒占空比DM15102
  channel_prefix: mid_lower_mid_heater
  connection_id: pwm_plc1
  connection_type: keyence
  data_type: uint16
  device_type: DM
  offset: 0
  quantity: 1
  scale: 1.0
  start_addr: 15102
  task_id: heater_duty_mid_lower_mid
  unit: '%'
- byte_order: abcd
  channel_name: 中层上面中间两个加热棒占空比DM15104
  channel_prefix: mid_upper_mid_heater
  connection_id: pwm_plc1
  connection_type: keyence
  data_type: uint16
  device_type: DM
  offset: 0
  quantity: 1
  scale: 1.0
  start_addr: 15104
  task_id: heater_duty_mid_upper_mid
  unit: '%'
- byte_order: abcd
  channel_name: 上层中间两个加热棒占空比DM15106
  channel_prefix: upper_mid_heater
  connection_id: pwm_plc1
  connection_type: keyence
  data_type: uint16
  device_type: DM
  offset: 0
  quantity: 1
  scale: 1.0
  start_addr: 15106
  task_id: heater_duty_upper_mid
  unit: '%'
- byte_order: abcd
  channel_name: CH1输出功率1
  channel_prefix: out1_ch1
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4208
  task_id: task_out1_ch1
  unit: '%'
- byte_order: abcd
  channel_name: CH2输出功率1
  channel_prefix: out1_ch2
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4209
  task_id: task_out1_ch2
  unit: '%'
- byte_order: abcd
  channel_name: CH3输出功率1
  channel_prefix: out1_ch3
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4210
  task_id: task_out1_ch3
  unit: '%'
- byte_order: abcd
  channel_name: CH4输出功率1
  channel_prefix: out1_ch4
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4211
  task_id: task_out1_ch4
  unit: '%'
- byte_order: abcd
  channel_name: CH5输出功率1
  channel_prefix: out1_ch5
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4212
  task_id: task_out1_ch5
  unit: '%'
- byte_order: abcd
  channel_name: CH6输出功率1
  channel_prefix: out1_ch6
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4213
  task_id: task_out1_ch6
  unit: '%'
- byte_order: abcd
  channel_name: CH7输出功率1
  channel_prefix: out1_ch7
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4214
  task_id: task_out1_ch7
  unit: '%'
- byte_order: abcd
  channel_name: CH8输出功率1
  channel_prefix: out1_ch8
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4215
  task_id: task_out1_ch8
  unit: '%'
- byte_order: abcd
  channel_name: CH3设定温度
  channel_prefix: sv_ch3
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4106
  task_id: task_sv_ch3
  unit: °C
- byte_order: abcd
  channel_name: CH4设定温度
  channel_prefix: sv_ch4
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4107
  task_id: task_sv_ch4
  unit: °C
write_tasks:
- byte_order: abcd
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: int16
  device_type: holding
  name: 第1路偏移量修正，单位：0.1℃
  start_addr: 22
  task_id: wtask_rtu_offset_ch1
  value: 10.0
  write_interval: 1.0
- byte_order: abcd
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: int16
  device_type: holding
  name: 第2路偏移量修正，单位：0.1℃
  start_addr: 23
  task_id: wtask_rtu_offset_ch2
  value: 10.0
  write_interval: 1.0
- byte_order: abcd
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: int16
  device_type: holding
  name: 第3路偏移量修正，单位：0.1℃
  start_addr: 24
  task_id: wtask_rtu_offset_ch3
  value: 10.0
  write_interval: 1.0
- byte_order: abcd
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: int16
  device_type: holding
  name: 第4路偏移量修正，单位：0.1℃
  start_addr: 25
  task_id: wtask_rtu_offset_ch4
  value: 10.0
  write_interval: 1.0
- byte_order: abcd
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: int16
  device_type: holding
  name: 第5路偏移量修正，单位：0.1℃
  start_addr: 26
  task_id: wtask_rtu_offset_ch5
  value: 10.0
  write_interval: 1.0
- byte_order: abcd
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: int16
  device_type: holding
  name: 第6路偏移量修正，单位：0.1℃
  start_addr: 27
  task_id: wtask_rtu_offset_ch6
  value: 10.0
  write_interval: 1.0
# - byte_order: abcd
#   connection_id: pwm_plc1
#   connection_type: keyence
#   data_type: uint16
#   device_type: DM
#   name: 写入下层中间两个加热棒占空比
#   start_addr: 15100
#   task_id: wtask_keyence_dm1
#   value: 50.0
#   write_interval: 1.0
# - byte_order: abcd
#   connection_id: pwm_plc1
#   connection_type: keyence
#   data_type: uint16
#   device_type: DM
#   name: 写入中层下面中间两个加热棒占空比
#   start_addr: 15102
#   task_id: wtask_keyence_dm2
#   value: 50.0
#   write_interval: 1.0
# - byte_order: abcd
#   connection_id: pwm_plc1
#   connection_type: keyence
#   data_type: uint16
#   device_type: DM
#   name: 写入中层上面中间两个加热棒占空比
#   start_addr: 15104
#   task_id: wtask_keyence_dm3
#   value: 50.0
#   write_interval: 1.0
# - byte_order: abcd
#   connection_id: pwm_plc1
#   connection_type: keyence
#   data_type: uint16
#   device_type: DM
#   name: 写入上层中间两个加热棒占空比
#   start_addr: 15106
#   task_id: wtask_keyence_dm4
#   value: 50.0
#   write_interval: 1.0
