calc_tasks:
# ========== 1层 下模具下层 CH1 CH2 (pt100物理：上模具下层 CH1 CH2 CH3 → task_temp_ch1/task_temp_ch2/task_temp_ch3) ==========
- channel_name: 1层下模具下层SV实时CH1
  channel_prefix: calc_live_ch1
  formula: min(max(task_sv_ch1*10+(175-task_temp_ch1)*10,1500),2500)
  offset: 0.0
  scale: 1.0
  task_id: calc_1785919067200
  unit: ℃
- channel_name: 1层下模具下层SV实时CH2
  channel_prefix: calc_live_ch2
  formula: min(max(task_sv_ch2*10+(task_temp_ch1-task_temp_ch3)*10,1500),2500)
  offset: 0.0
  scale: 1.0
  task_id: calc_live_ch2_1785919067201
  unit: ℃
- channel_name: 1层下模具下层SV实时CH1与实际温度差
  channel_prefix: calc_live_ch1_diff
  formula: task_sv_ch1-task_temp_ch1
  offset: 0.0
  scale: 1.0
  task_id: calc_1785919067204
  unit: ℃
- channel_name: 1层下模具下层倾斜(CH1‑CH3)
  channel_prefix: calc_lower_tilt
  formula: task_temp_ch1-task_temp_ch3
  offset: 0.0
  scale: 1.0
  task_id: calc_1785919067202
  unit: ℃
- channel_name: 1层下模具下层中心差 ((CH2*2‑CH1‑CH3)*0.5)
  channel_prefix: calc_lower_center_diff
  formula: (task_temp_ch2*2-task_temp_ch1-task_temp_ch3)*0.5
  offset: 0.0
  scale: 1.0
  task_id: calc_center_1785919067208
  unit: ℃
- channel_name: 1层下模具下层PWM调节值
  channel_prefix: calc_lower_pwm
  formula: min(max((heater_duty_lower_mid-(task_temp_ch2*2-task_temp_ch1-task_temp_ch3)*0.5),0),100)
  offset: 0.0
  scale: 1.0
  task_id: calc_pwm_1785919067209
  unit: '%'

# ========== 2层 下模具上层 CH3 CH4 (pt100物理：上模具上层 CH4 CH5 CH6 → task_temp_ch4/task_temp_ch5/task_temp_ch6) ==========
- channel_name: 2层下模具上层SV实时CH3
  channel_prefix: calc_live_ch3
  formula: min(max(task_sv_ch3*10+(175-task_temp_ch4)*10,1500),2500)
  offset: 0.0
  scale: 1.0
  task_id: calc_1785919067203
  unit: ℃
- channel_name: 2层下模具上层SV实时CH4
  channel_prefix: calc_live_ch4
  formula: min(max(task_sv_ch4*10+(task_temp_ch4-task_temp_ch6)*10,1500),2500)
  offset: 0.0
  scale: 1.0
  task_id: calc_live_ch4_1785919067204
  unit: ℃
- channel_name: 2层下模具上层SV实时CH3与实际温度差
  channel_prefix: calc_live_ch3_diff
  formula: task_sv_ch3-task_temp_ch4
  offset: 0.0
  scale: 1.0
  task_id: calc_1785919067205
  unit: ℃
- channel_name: 2层下模具上层倾斜(CH4‑CH6)
  channel_prefix: calc_upper_tilt
  formula: task_temp_ch4-task_temp_ch6
  offset: 0.0
  scale: 1.0
  task_id: calc_1785919067206
  unit: ℃
- channel_name: 2层下模具上层中心差 ((CH5*2‑CH4‑CH6)*0.5)
  channel_prefix: calc_upper_center_diff
  formula: (task_temp_ch5*2-task_temp_ch4-task_temp_ch6)*0.5
  offset: 0.0
  scale: 1.0
  task_id: calc_center_1785919067207
  unit: ℃
- channel_name: 2层下模具上层PWM调节值
  channel_prefix: calc_mid_lower_pwm
  formula: min(max((heater_duty_mid_lower_mid-(task_temp_ch5*2-task_temp_ch4-task_temp_ch6)*0.5),0),100)
  offset: 0.0
  scale: 1.0
  task_id: calc_pwm_1785919067210
  unit: '%'

# ========== 3层 上模具下层 CH5 CH6 ==========
- channel_name: 3层上模具下层SV实时CH5
  channel_prefix: calc_live_ch5
  formula: min(max(task_sv_ch5*10+(175-task_temp_ch1)*10,1500),2500)
  offset: 0.0
  scale: 1.0
  task_id: calc_live_ch5_1785919067211
  unit: ℃
- channel_name: 3层上模具下层SV实时CH6
  channel_prefix: calc_live_ch6
  formula: min(max(task_sv_ch6*10+(task_temp_ch1-task_temp_ch3)*10,1500),2500)
  offset: 0.0
  scale: 1.0
  task_id: calc_live_ch6_1785919067212
  unit: ℃

# ========== 4层 上模具上层 CH7 CH8 ==========
- channel_name: 4层上模具上层SV实时CH7
  channel_prefix: calc_live_ch7
  formula: min(max(task_sv_ch7*10+(175-task_temp_ch4)*10,1500),2500)
  offset: 0.0
  scale: 1.0
  task_id: calc_live_ch7_1785919067213
  unit: ℃
- channel_name: 4层上模具上层SV实时CH8
  channel_prefix: calc_live_ch8
  formula: min(max(task_sv_ch8*10+(task_temp_ch4-task_temp_ch6)*10,1500),2500)
  offset: 0.0
  scale: 1.0
  task_id: calc_live_ch8_1785919067214
  unit: ℃

calc_write_tasks:
# 1层 下模具下层 CH1 CH2  4104、4105
- byte_order: abcd
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  name: 设置1层下模具下层CH1设定温度SV
  source_task_id: calc_1785919067200
  start_addr: 4104
  task_id: calcwrite_1785919993452
  write_interval: 1500.0
- byte_order: abcd
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  name: 设置1层下模具下层CH2设定温度SV
  source_task_id: calc_live_ch2_1785919067201
  start_addr: 4105
  task_id: calc_write_sv_ch2_1785919993453
  write_interval: 1500.0

# 2层 下模具上层 CH3 CH4 4106、4107
- byte_order: abcd
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  name: 设置2层下模具上层CH3设定温度SV
  source_task_id: calc_1785919067203
  start_addr: 4106
  task_id: calc_write_sv_ch3_1785919993454
  write_interval: 1500.0
- byte_order: abcd
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  name: 设置2层下模具上层CH4设定温度SV
  source_task_id: calc_live_ch4_1785919067204
  start_addr: 4107
  task_id: calc_write_sv_ch4_1785919993455
  write_interval: 1500.0

# 3层 上模具下层 CH5 CH6 4108、4109
- byte_order: abcd
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  name: 设置3层上模具下层CH5设定温度SV
  source_task_id: calc_live_ch5_1785919067211
  start_addr: 4108
  task_id: calc_write_sv_ch5_1785919993456
  write_interval: 1500.0
- byte_order: abcd
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  name: 设置3层上模具下层CH6设定温度SV
  source_task_id: calc_live_ch6_1785919067212
  start_addr: 4109
  task_id: calc_write_sv_ch6_1785919993457
  write_interval: 1500.0

# 4层 上模具上层 CH7 CH8 4110、4111
- byte_order: abcd
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  name: 设置4层上模具上层CH7设定温度SV
  source_task_id: calc_live_ch7_1785919067213
  start_addr: 4110
  task_id: calc_write_sv_ch7_1785919993458
  write_interval: 1500.0
- byte_order: abcd
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  name: 设置4层上模具上层CH8设定温度SV
  source_task_id: calc_live_ch8_1785919067214
  start_addr: 4111
  task_id: calc_write_sv_ch8_1785919993459
  write_interval: 1500.0

# PWM输出到基恩士PLC保持不变
- byte_order: abcd
  connection_id: pwm_plc1
  connection_type: keyence
  data_type: uint16
  device_type: DM
  name: 下模下层PWM调节值
  source_task_id: calc_pwm_1785919067209
  start_addr: 15100
  task_id: pwm_pwm
  write_interval: 1500.0
- byte_order: abcd
  connection_id: pwm_plc1
  connection_type: keyence
  data_type: uint16
  device_type: DM
  name: 中层下面PWM调节值
  source_task_id: calc_pwm_1785919067210
  start_addr: 15102
  task_id: pwm_mid_lower
  write_interval: 1500.0

connections:
  dte_rtu_com9:
    params:
      baudrate: 115200
      bytesize: 8
      parity: E
      port: COM9
      slave_id: 1
      stopbits: 1
      timeout: 1.0
    type: modbus_rtu
  pt100_rtu_com11:
    params:
      baudrate: 9600
      bytesize: 8
      parity: N
      port: COM11
      slave_id: 0
      stopbits: 1
      timeout: 1.0
    type: modbus_rtu
  pwm_plc1:
    params:
      host: 192.168.2.80
      port: 8501
      timeout: 3.0
      unit: 0
    type: keyence

poll_interval: 10.0

tasks:
# ========= PT100 1‑6路物理贴片分布更新描述，寄存器地址不变 =========
- byte_order: abcd
  channel_name: 第1路温度（上模具下层‑CH1）
  channel_prefix: temp_ch1
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.01
  start_addr: 0
  task_id: task_temp_ch1
  unit: °C
- byte_order: abcd
  channel_name: 第2路温度（上模具下层‑CH2）
  channel_prefix: temp_ch2
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.01
  start_addr: 1
  task_id: task_temp_ch2
  unit: °C
- byte_order: abcd
  channel_name: 第3路温度（上模具下层‑CH3）
  channel_prefix: temp_ch3
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.01
  start_addr: 2
  task_id: task_temp_ch3
  unit: °C
- byte_order: abcd
  channel_name: 第4路温度（上模具上层‑CH4）
  channel_prefix: temp_ch4
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.01
  start_addr: 3
  task_id: task_temp_ch4
  unit: °C
- byte_order: abcd
  channel_name: 第5路温度（上模具上层‑CH5）
  channel_prefix: temp_ch5
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.01
  start_addr: 4
  task_id: task_temp_ch5
  unit: °C
- byte_order: abcd
  channel_name: 第6路温度（上模具上层‑CH6）
  channel_prefix: temp_ch6
  connection_id: pt100_rtu_com11
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.01
  start_addr: 5
  task_id: task_temp_ch6
  unit: °C

# ========= SV设定值读取 CH1~CH8，更新channel_name层位说明 =========
- byte_order: abcd
  channel_name: CH1设定温度（1层‑下模具下层）
  channel_prefix: sv_ch1
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4104
  task_id: task_sv_ch1
  unit: °C
- byte_order: abcd
  channel_name: CH2设定温度（1层‑下模具下层）
  channel_prefix: sv_ch2
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4105
  task_id: task_sv_ch2
  unit: °C
- byte_order: abcd
  channel_name: CH3设定温度（2层‑下模具上层）
  channel_prefix: sv_ch3
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4106
  task_id: task_sv_ch3
  unit: °C
- byte_order: abcd
  channel_name: CH4设定温度（2层‑下模具上层）
  channel_prefix: sv_ch4
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4107
  task_id: task_sv_ch4
  unit: °C
- byte_order: abcd
  channel_name: CH5设定温度（3层‑上模具下层）
  channel_prefix: sv_ch5
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4108
  task_id: task_sv_ch5
  unit: °C
- byte_order: abcd
  channel_name: CH6设定温度（3层‑上模具下层）
  channel_prefix: sv_ch6
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4109
  task_id: task_sv_ch6
  unit: °C
- byte_order: abcd
  channel_name: CH7设定温度（4层‑上模具上层）
  channel_prefix: sv_ch7
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4110
  task_id: task_sv_ch7
  unit: °C
- byte_order: abcd
  channel_name: CH8设定温度（4层‑上模具上层）
  channel_prefix: sv_ch8
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4111
  task_id: task_sv_ch8
  unit: °C

# ========= 基恩士PLC PWM占空比读取 =========
- byte_order: abcd
  channel_name: 下模下层中间两个加热棒占空比DM15100
  channel_prefix: lower_mid_heater
  connection_id: pwm_plc1
  connection_type: keyence
  data_type: uint16
  device_type: DM
  offset: 0
  quantity: 1
  scale: 1.0
  start_addr: 15100
  task_id: heater_duty_lower_mid
  unit: '%'
- byte_order: abcd
  channel_name: 中层下面中间两个加热棒占空比DM15102
  channel_prefix: mid_lower_mid_heater
  connection_id: pwm_plc1
  connection_type: keyence
  data_type: uint16
  device_type: DM
  offset: 0
  quantity: 1
  scale: 1.0
  start_addr: 15102
  task_id: heater_duty_mid_lower_mid
  unit: '%'
- byte_order: abcd
  channel_name: 中层上面中间两个加热棒占空比DM15104
  channel_prefix: mid_upper_mid_heater
  connection_id: pwm_plc1
  connection_type: keyence
  data_type: uint16
  device_type: DM
  offset: 0
  quantity: 1
  scale: 1.0
  start_addr: 15104
  task_id: heater_duty_mid_upper_mid
  unit: '%'
- byte_order: abcd
  channel_name: 下模上层中间两个加热棒占空比DM15106
  channel_prefix: upper_mid_heater
  connection_id: pwm_plc1
  connection_type: keyence
  data_type: uint16
  device_type: DM
  offset: 0
  quantity: 1
  scale: 1.0
  start_addr: 15106
  task_id: heater_duty_upper_mid
  unit: '%'

# ========= CH1‑CH8输出功率读取 =========
- byte_order: abcd
  channel_name: CH1输出功率1
  channel_prefix: out1_ch1
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4208
  task_id: task_out1_ch1
  unit: '%'
- byte_order: abcd
  channel_name: CH2输出功率1
  channel_prefix: out1_ch2
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4209
  task_id: task_out1_ch2
  unit: '%'
- byte_order: abcd
  channel_name: CH3输出功率1
  channel_prefix: out1_ch3
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4210
  task_id: task_out1_ch3
  unit: '%'
- byte_order: abcd
  channel_name: CH4输出功率1
  channel_prefix: out1_ch4
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4211
  task_id: task_out1_ch4
  unit: '%'
- byte_order: abcd
  channel_name: CH5输出功率1
  channel_prefix: out1_ch5
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4212
  task_id: task_out1_ch5
  unit: '%'
- byte_order: abcd
  channel_name: CH6输出功率1
  channel_prefix: out1_ch6
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4213
  task_id: task_out1_ch6
  unit: '%'
- byte_order: abcd
  channel_name: CH7输出功率1
  channel_prefix: out1_ch7
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4214
  task_id: task_out1_ch7
  unit: '%'
- byte_order: abcd
  channel_name: CH8输出功率1
  channel_prefix: out1_ch8
  connection_id: dte_rtu_com9
  connection_type: modbus_rtu
  data_type: uint16
  device_type: holding
  offset: 0
  quantity: 1
  scale: 0.1
  start_addr: 4215
  task_id: task_out1_ch8
  unit: '%'
